# Generated by Django 5.2.8 on 2026-01-20 07:53

import apps.models.base
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('requirement_id', models.CharField(max_length=50, unique=True, verbose_name='需求ID')),
                ('origin_name', models.CharField(max_length=100, verbose_name='出发地名称')),
                ('origin_code', models.CharField(blank=True, max_length=10, verbose_name='出发地代码')),
                ('origin_type', models.CharField(blank=True, max_length=20, verbose_name='出发地类型')),
                ('destination_cities', apps.models.base.JSONField(default=list, verbose_name='目的地城市列表')),
                ('trip_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='出行天数')),
                ('group_adults', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成人数量')),
                ('group_children', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='儿童数量')),
                ('group_seniors', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='老人数量')),
                ('group_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='总人数')),
                ('travel_start_date', models.DateField(verbose_name='出行开始日期')),
                ('travel_end_date', models.DateField(verbose_name='出行结束日期')),
                ('travel_date_flexible', models.BooleanField(default=False, verbose_name='日期是否灵活')),
                ('transportation_type', models.CharField(blank=True, choices=[('RoundTripFlight', '双飞'), ('OneWayFlight', '单飞'), ('HighSpeedTrain', '高铁'), ('Train', '火车'), ('SelfDriving', '自驾'), ('Other', '其他')], max_length=20, verbose_name='大交通方式')),
                ('transportation_notes', models.TextField(blank=True, verbose_name='交通偏好说明')),
                ('hotel_level', models.CharField(blank=True, choices=[('Economy', '经济型'), ('Comfort', '舒适型'), ('Premium', '高档型'), ('Luxury', '豪华型')], max_length=20, verbose_name='酒店等级')),
                ('hotel_requirements', models.TextField(blank=True, verbose_name='住宿特殊要求')),
                ('trip_rhythm', models.CharField(blank=True, choices=[('Relaxed', '悠闲'), ('Moderate', '适中'), ('Intense', '紧凑')], max_length=20, verbose_name='行程节奏')),
                ('preference_tags', apps.models.base.JSONField(default=list, verbose_name='偏好标签')),
                ('must_visit_spots', apps.models.base.JSONField(default=list, verbose_name='必游景点')),
                ('avoid_activities', apps.models.base.JSONField(default=list, verbose_name='避免活动')),
                ('budget_level', models.CharField(blank=True, choices=[('Economy', '经济'), ('Comfort', '舒适'), ('HighEnd', '高端'), ('Luxury', '奢华')], max_length=20, verbose_name='预算等级')),
                ('budget_currency', models.CharField(default='CNY', max_length=10, verbose_name='预算货币')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低预算')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高预算')),
                ('budget_notes', models.TextField(blank=True, verbose_name='预算说明')),
                ('source_type', models.CharField(choices=[('NaturalLanguage', '自然语言输入'), ('FormInput', '表单输入')], default='NaturalLanguage', max_length=20, verbose_name='需求来源')),
                ('status', models.CharField(choices=[('PendingReview', '待审核'), ('Confirmed', '已确认'), ('Expired', '已过期')], default='PendingReview', max_length=20, verbose_name='需求状态')),
                ('assumptions', apps.models.base.JSONField(default=list, verbose_name='系统推断说明')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='创建人')),
                ('reviewed_by', models.CharField(blank=True, max_length=100, verbose_name='审核人')),
                ('is_template', models.BooleanField(default=False, verbose_name='是否模板')),
                ('template_name', models.CharField(blank=True, max_length=200, verbose_name='模板名称')),
                ('template_category', models.CharField(blank=True, max_length=100, verbose_name='模板分类')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('extension', apps.models.base.JSONField(default=dict, verbose_name='扩展字段')),
            ],
            options={
                'verbose_name': '旅游需求',
                'verbose_name_plural': '旅游需求',
                'db_table': 'requirements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requirement_id'], name='requirement_require_d528d1_idx'), models.Index(fields=['status'], name='requirement_status_b8bfb6_idx'), models.Index(fields=['created_by'], name='requirement_created_d3ee3d_idx'), models.Index(fields=['is_template'], name='requirement_is_temp_d1d097_idx'), models.Index(fields=['-created_at'], name='requirement_created_0ede4d_idx')],
            },
        ),
    ]
