# Generated by Django 5.2.8 on 2026-01-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='审核人'),
        ),
    ]
