# Generated by Django 5.2.8 on 2026-01-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_requirement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='travel_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='出行结束日期'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='travel_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='出行开始日期'),
        ),
    ]
