# Generated by Django 5.2.8 on 2026-01-21 10:41

import apps.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_requirement_travel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='origin_input',
            field=models.TextField(blank=True, verbose_name='客户原始输入'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_json_data',
            field=apps.models.base.JSONField(default=dict, verbose_name='JSON结构数据'),
        ),
    ]
