# Generated by Django 5.2.8 on 2026-01-29 09:02

import apps.models.base
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_attraction_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hotel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='酒店ID')),
                ('hotel_code', models.CharField(max_length=50, unique=True, verbose_name='酒店代码')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='酒店名称')),
                ('brand_name', models.CharField(blank=True, max_length=100, verbose_name='品牌名称')),
                ('country_code', models.CharField(max_length=2, verbose_name='国家代码')),
                ('city_name', models.CharField(max_length=100, verbose_name='城市名称')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='区域')),
                ('address', models.TextField(verbose_name='地址')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度')),
                ('hotel_star', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='星级')),
                ('hotel_type', models.CharField(blank=True, choices=[('LUXURY', '奢华酒店'), ('BUSINESS', '商务酒店'), ('RESORT', '度假酒店'), ('BOUTIQUE', '精品酒店'), ('HOSTEL', '青年旅舍'), ('APARTMENT', '公寓酒店'), ('HOMESTAY', '民宿'), ('MOTEL', '汽车旅馆'), ('OTHER', '其他')], max_length=50, verbose_name='酒店类型')),
                ('tags', apps.models.base.JSONField(default=dict, verbose_name='标签')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='入住时间')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='退房时间')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, max_length=255, verbose_name='联系邮箱')),
                ('website', models.CharField(blank=True, max_length=500, verbose_name='网站')),
                ('amenities', apps.models.base.JSONField(default=dict, verbose_name='设施')),
                ('room_facilities', apps.models.base.JSONField(default=dict, verbose_name='房间设施')),
                ('business_facilities', apps.models.base.JSONField(default=dict, verbose_name='商务设施')),
                ('room_types', apps.models.base.JSONField(default=dict, verbose_name='房型信息')),
                ('price_range', models.CharField(blank=True, max_length=50, verbose_name='价格范围')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低价格')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高价格')),
                ('popularity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='受欢迎度评分')),
                ('guest_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='客人评分')),
                ('review_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('main_image_url', models.CharField(blank=True, max_length=500, verbose_name='主图URL')),
                ('image_gallery', apps.models.base.JSONField(default=list, verbose_name='图片库')),
                ('status', models.CharField(choices=[('ACTIVE', '营业中'), ('INACTIVE', '未营业'), ('RENOVATING', '装修中'), ('CLOSED', '已关闭')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('created_by', models.CharField(blank=True, max_length=50, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=50, verbose_name='更新人')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
            ],
            options={
                'verbose_name': '酒店',
                'verbose_name_plural': '酒店',
                'db_table': 'hotels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel_code'], name='hotels_hotel_c_11ea8d_idx'), models.Index(fields=['hotel_name'], name='hotels_hotel_n_1f9352_idx'), models.Index(fields=['country_code'], name='hotels_country_ff3fc3_idx'), models.Index(fields=['city_name'], name='hotels_city_na_e3bbe2_idx'), models.Index(fields=['hotel_star'], name='hotels_hotel_s_b29386_idx'), models.Index(fields=['hotel_type'], name='hotels_hotel_t_6ed60f_idx'), models.Index(fields=['status'], name='hotels_status_9c7b12_idx'), models.Index(fields=['-created_at'], name='hotels_created_1d9e51_idx')],
            },
        ),
    ]
