# Generated by Django 5.2.8 on 2026-01-30 05:59

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('itinerary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='行程唯一标识')),
                ('itinerary_name', models.CharField(max_length=100, verbose_name='行程名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='行程描述')),
                ('travel_purpose', models.CharField(choices=[('LEISURE', '休闲'), ('BUSINESS', '商务'), ('HONEYMOON', '蜜月'), ('FAMILY', '家庭'), ('ADVENTURE', '冒险'), ('CULTURAL', '文化'), ('OTHER', '其他')], max_length=20, verbose_name='旅行目的')),
                ('start_date', models.DateField(verbose_name='行程开始日期')),
                ('end_date', models.DateField(verbose_name='行程结束日期')),
                ('total_days', models.IntegerField(verbose_name='总天数')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人单位')),
                ('departure_city', models.CharField(max_length=100, verbose_name='出发城市')),
                ('return_city', models.CharField(max_length=100, verbose_name='返回城市')),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总预算')),
                ('budget_flexibility', models.CharField(blank=True, choices=[('STRICT', '严格'), ('MODERATE', '适中'), ('FLEXIBLE', '灵活')], max_length=10, null=True, verbose_name='预算灵活性')),
                ('current_status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('CONFIRMED', '已确认'), ('EXPIRED', '已过期'), ('CANCELLED', '已取消'), ('COMPLETED', '已完成')], max_length=20, verbose_name='当前状态')),
                ('review_deadline', models.DateTimeField(blank=True, null=True, verbose_name='审核截止时间')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='行程有效期截止日期')),
                ('confirmed_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='确认人（运营人员）')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('is_template', models.BooleanField(default=False, verbose_name='是否为模板')),
                ('template_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='模板名称')),
                ('template_category', models.CharField(blank=True, choices=[('HONEYMOON', '蜜月'), ('FAMILY', '家庭'), ('ADVENTURE', '冒险'), ('CITY_TOUR', '城市游览'), ('BEACH', '海滩'), ('CULTURAL', '文化'), ('CUSTOM', '自定义')], max_length=20, null=True, verbose_name='模板分类')),
                ('usage_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='模板使用次数')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='模板最后使用时间')),
                ('created_by', models.CharField(max_length=50, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '行程主表',
                'verbose_name_plural': '行程主表',
                'db_table': 'itinerary',
            },
        ),
    ]
