# Generated by Django 5.2.8 on 2026-01-30 06:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelerStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='统计ID')),
                ('adult_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成人数')),
                ('child_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='儿童数')),
                ('infant_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='婴儿数')),
                ('senior_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='老人数')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_stats', to='apps.itinerary', verbose_name='行程')),
            ],
            options={
                'verbose_name': '出行人员统计表',
                'verbose_name_plural': '出行人员统计表',
                'db_table': 'traveler_stats',
            },
        ),
    ]
