# Generated by Django 5.2.8 on 2026-01-30 06:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_travelerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('destination_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='目的地ID')),
                ('destination_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='目的地顺序')),
                ('city_name', models.CharField(max_length=100, verbose_name='城市名称')),
                ('country_code', models.CharField(max_length=2, verbose_name='国家代码')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='地区（如省、州）')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='经度')),
                ('arrival_date', models.DateField(verbose_name='抵达日期')),
                ('departure_date', models.DateField(verbose_name='离开日期')),
                ('nights', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='住宿晚数')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='apps.itinerary', verbose_name='行程')),
            ],
            options={
                'verbose_name': '目的地表',
                'verbose_name_plural': '目的地表',
                'db_table': 'destinations',
            },
        ),
    ]
