# Generated by Django 5.2.8 on 2026-01-30 06:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='活动ID')),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='第几天')),
                ('schedule_date', models.DateField(verbose_name='活动日期')),
                ('city_name', models.CharField(max_length=100, verbose_name='城市名称')),
                ('activity_type', models.CharField(choices=[('FLIGHT', '航班'), ('TRAIN', '火车'), ('ATTRACTION', '景点'), ('MEAL', '餐饮'), ('TRANSPORT', '交通'), ('SHOPPING', '购物'), ('FREE', '自由活动'), ('CHECK_IN', '入住'), ('CHECK_OUT', '退房'), ('OTHER', '其他')], max_length=30, verbose_name='活动类型')),
                ('activity_title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('activity_description', models.TextField(blank=True, null=True, verbose_name='活动描述')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='预估费用')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('booking_status', models.CharField(blank=True, choices=[('NOT_BOOKED', '未预订'), ('PENDING', '待确认'), ('CONFIRMED', '已确认'), ('CANCELLED', '已取消')], max_length=15, null=True, verbose_name='预订状态')),
                ('booking_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='预订参考号')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('attraction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.attraction', verbose_name='关联景点ID')),
                ('hotel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.hotel', verbose_name='关联酒店ID')),
                ('itinerary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.itinerary', verbose_name='行程ID')),
                ('restaurant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.restaurant', verbose_name='关联餐厅ID')),
            ],
            options={
                'verbose_name': '每日行程活动表',
                'verbose_name_plural': '每日行程活动表',
                'db_table': 'daily_schedules',
                'ordering': ['itinerary_id', 'day_number', 'start_time'],
                'indexes': [models.Index(fields=['itinerary_id'], name='daily_sched_itinera_cb13ef_idx'), models.Index(fields=['schedule_date'], name='daily_sched_schedul_55b5ce_idx'), models.Index(fields=['city_name'], name='daily_sched_city_na_2e042a_idx'), models.Index(fields=['activity_type'], name='daily_sched_activit_ec2ddf_idx'), models.Index(fields=['attraction_id'], name='daily_sched_attract_b39702_idx'), models.Index(fields=['hotel_id'], name='daily_sched_hotel_i_6c304e_idx'), models.Index(fields=['restaurant_id'], name='daily_sched_restaur_225a70_idx')],
            },
        ),
    ]
