# Generated by Django 5.2.10 on 2026-01-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_dailyschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'verbose_name': '景点数据', 'verbose_name_plural': '景点数据'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-created_at'], 'verbose_name': '酒店数据', 'verbose_name_plural': '酒店数据'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name': '旅游行程规划', 'verbose_name_plural': '旅游行程规划'},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['-created_at'], 'verbose_name': '旅游需求管理', 'verbose_name_plural': '旅游需求管理'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-created_at'], 'verbose_name': '餐厅数据', 'verbose_name_plural': '餐厅数据'},
        ),
    ]
