# Generated by Django 5.2.8 on 2026-01-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_attraction_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='itinerary_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='行程唯一标识'),
        ),
    ]
