# Generated by Django 5.2.8 on 2026-02-02 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_itinerary_itinerary_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyschedule',
            name='daily_sched_city_na_2e042a_idx',
        ),
        migrations.RemoveField(
            model_name='dailyschedule',
            name='city_name',
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='destination_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.destination', verbose_name='目的地ID'),
        ),
        migrations.AddIndex(
            model_name='dailyschedule',
            index=models.Index(fields=['destination_id'], name='daily_sched_destina_1d1239_idx'),
        ),
    ]
