# Generated by Django 5.2.8 on 2026-02-11 14:19

import apps.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_remove_dailyschedule_daily_sched_city_na_2e042a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='id',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='itinerary_json_data',
            field=models.JSONField(blank=True, null=True, verbose_name='行程结构化JSON数据'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='avoid_activities',
            field=apps.models.base.JSONField(blank=True, default=list, verbose_name='避免活动'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='extension',
            field=apps.models.base.JSONField(blank=True, default=dict, verbose_name='扩展字段'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='must_visit_spots',
            field=apps.models.base.JSONField(blank=True, default=list, verbose_name='必游景点'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='preference_tags',
            field=apps.models.base.JSONField(blank=True, default=list, verbose_name='偏好标签'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='需求ID'),
        ),
    ]
