# Generated by Django 5.2.10 on 2026-02-13 06:53

import apps.models.base
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_remove_requirement_id_itinerary_itinerary_json_data_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='attraction',
            table_comment='景点信息表,存储全球旅游景点的详细信息,包括景点基本信息、门票价格、开放时间、设施服务、评分评价等数据',
        ),
        migrations.AlterModelTableComment(
            name='dailyschedule',
            table_comment='每日行程活动表,存储行程中每一天的具体活动安排,包括航班、景点游览、餐饮、交通等活动的详细信息',
        ),
        migrations.AlterModelTableComment(
            name='destination',
            table_comment='行程目的地表,存储行程中包含的所有目的地城市信息,包括地理位置、抵达离开日期、住宿晚数等',
        ),
        migrations.AlterModelTableComment(
            name='hotel',
            table_comment='酒店信息表,存储全球酒店住宿的详细信息,包括酒店基本信息、房型设施、价格范围、评分评价等数据',
        ),
        migrations.AlterModelTableComment(
            name='itinerary',
            table_comment='旅游行程规划主表,存储完整的旅游行程信息,包括行程基本信息、预算、状态、模板等核心数据',
        ),
        migrations.AlterModelTableComment(
            name='requirement',
            table_comment='旅游需求管理表,存储客户的旅游需求信息,包括出发地、目的地、出行人数、日期、预算、偏好等详细需求',
        ),
        migrations.AlterModelTableComment(
            name='restaurant',
            table_comment='餐厅信息表,存储全球餐厅餐饮的详细信息,包括餐厅基本信息、菜系类型、价格范围、评分评价等数据',
        ),
        migrations.AlterModelTableComment(
            name='travelerstats',
            table_comment='出行人员统计表,存储行程中出行人员的分类统计信息,包括成人、儿童、婴儿、老人等人数统计',
        ),
        migrations.AlterField(
            model_name='attraction',
            name='address',
            field=models.TextField(blank=True, db_comment='景点详细地址', null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attraction_code',
            field=models.CharField(db_comment='景点唯一编码,用于系统内部标识和检索', max_length=50, unique=True, verbose_name='景点代码'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attraction_id',
            field=models.UUIDField(db_comment='景点唯一标识符,使用UUID格式', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='景点ID'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attraction_name',
            field=models.CharField(db_comment='景点中文名称', max_length=200, verbose_name='景点名称'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='best_season',
            field=models.CharField(blank=True, db_comment='最佳游览季节', max_length=50, null=True, verbose_name='最佳季节'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='booking_required',
            field=models.BooleanField(db_comment='标识是否需要提前预订', default=False, verbose_name='是否需要预订'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='booking_website',
            field=models.CharField(blank=True, db_comment='官方预订网站URL', max_length=500, null=True, verbose_name='预订网站'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='category',
            field=models.CharField(blank=True, choices=[('NATURAL', 'Natural'), ('HISTORICAL', 'Historical'), ('CULTURAL', 'Cultural'), ('RELIGIOUS', 'Religious'), ('MODERN', 'Modern'), ('ENTERTAINMENT', 'Entertainment'), ('SHOPPING', 'Shopping'), ('OUTDOOR', 'Outdoor'), ('INDOOR', 'Indoor'), ('OTHER', 'Other')], db_comment='景点主分类,如自然景观、历史古迹、文化景点等', max_length=50, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='city_name',
            field=models.CharField(db_comment='景点所在城市名称', max_length=100, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='country_code',
            field=models.CharField(db_comment='所在国家的ISO 3166-1 alpha-2代码,如CN、US等', max_length=2, verbose_name='国家代码'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='created_by',
            field=models.CharField(blank=True, db_comment='记录创建人用户名', max_length=50, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='currency',
            field=models.CharField(db_comment='价格货币代码,如CNY、USD等', default='CNY', max_length=3, verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True, db_comment='景点详细描述介绍', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='facilities',
            field=apps.models.base.JSONField(blank=True, db_comment='景点设施列表,如停车场、餐厅、洗手间等', null=True, verbose_name='设施'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='highlights',
            field=apps.models.base.JSONField(blank=True, db_comment='景点特色亮点列表', null=True, verbose_name='景点特色'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='image_gallery',
            field=apps.models.base.JSONField(blank=True, db_comment='景点图片库URL数组', null=True, verbose_name='图片库'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='is_always_open',
            field=models.BooleanField(db_comment='标识景点是否全天开放', default=False, verbose_name='是否24小时开放'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='main_image_url',
            field=models.CharField(blank=True, db_comment='景点主图片URL', max_length=500, null=True, verbose_name='主图URL'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='opening_hours',
            field=apps.models.base.JSONField(blank=True, db_comment='开放时间JSON数据,包含每日开放时段', null=True, verbose_name='开放时间'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='popularity_score',
            field=models.DecimalField(blank=True, db_comment='景点受欢迎度评分,范围0-5', decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='受欢迎度评分'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='recommended_duration',
            field=models.IntegerField(blank=True, db_comment='建议游玩时长,单位为分钟', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='建议游玩时长（分钟）'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='region',
            field=models.CharField(blank=True, db_comment='景点所在地区或省份', max_length=100, null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='review_count',
            field=models.IntegerField(db_comment='累计评论数量', default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('CLOSED', 'Closed')], db_comment='景点当前状态,如营业中、关闭、维修中等', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='subcategory',
            field=models.CharField(blank=True, db_comment='景点子分类,用于更精细的分类', max_length=50, null=True, verbose_name='子分类'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='tags',
            field=apps.models.base.JSONField(blank=True, db_comment='景点标签数组,存储关键词如亲子、拍照、必游等', null=True, verbose_name='标签数组'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='ticket_price',
            field=models.DecimalField(blank=True, db_comment='门票价格', decimal_places=2, max_digits=10, null=True, verbose_name='门票价格'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='ticket_type',
            field=models.CharField(blank=True, db_comment='门票类型,如成人票、儿童票、套票等', max_length=50, null=True, verbose_name='票种'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='updated_by',
            field=models.CharField(blank=True, db_comment='记录更新人用户名', max_length=50, null=True, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='version',
            field=models.IntegerField(db_comment='数据版本号,用于版本控制', default=1, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='video_url',
            field=models.CharField(blank=True, db_comment='景点宣传视频URL', max_length=500, null=True, verbose_name='视频URL'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='visitor_rating',
            field=models.DecimalField(blank=True, db_comment='游客综合评分,范围0-5', decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='游客评分'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='activity_description',
            field=models.TextField(blank=True, db_comment='活动详细描述', null=True, verbose_name='活动描述'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='activity_title',
            field=models.CharField(db_comment='活动标题名称', max_length=200, verbose_name='活动标题'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='activity_type',
            field=models.CharField(choices=[('FLIGHT', '航班'), ('TRAIN', '火车'), ('ATTRACTION', '景点'), ('MEAL', '餐饮'), ('TRANSPORT', '交通'), ('SHOPPING', '购物'), ('FREE', '自由活动'), ('CHECK_IN', '入住'), ('CHECK_OUT', '退房'), ('OTHER', '其他')], db_comment='活动类型,如航班、景点、餐饮、交通等', max_length=30, verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='attraction_id',
            field=models.ForeignKey(blank=True, db_comment='关联的景点ID,外键关联attractions表', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.attraction', verbose_name='关联景点ID'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='booking_reference',
            field=models.CharField(blank=True, db_comment='预订订单号或参考号', max_length=100, null=True, verbose_name='预订参考号'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('NOT_BOOKED', '未预订'), ('PENDING', '待确认'), ('CONFIRMED', '已确认'), ('CANCELLED', '已取消')], db_comment='预订状态,如未预订、待确认、已确认、已取消', max_length=15, null=True, verbose_name='预订状态'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='currency',
            field=models.CharField(db_comment='费用货币代码,如CNY、USD等', default='CNY', max_length=3, verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='day_number',
            field=models.IntegerField(db_comment='行程中的第几天,从1开始计数', validators=[django.core.validators.MinValueValidator(1)], verbose_name='第几天'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='destination_id',
            field=models.ForeignKey(blank=True, db_comment='关联的目的地ID,外键关联destinations表', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.destination', verbose_name='目的地ID'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='end_time',
            field=models.TimeField(db_comment='活动结束时间', verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='estimated_cost',
            field=models.DecimalField(blank=True, db_comment='该活动的预估费用', decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='预估费用'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='hotel_id',
            field=models.ForeignKey(blank=True, db_comment='关联的酒店ID,外键关联hotels表', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.hotel', verbose_name='关联酒店ID'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='itinerary_id',
            field=models.ForeignKey(db_comment='关联的行程ID,外键关联itinerary表', on_delete=django.db.models.deletion.CASCADE, to='apps.itinerary', verbose_name='行程ID'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='notes',
            field=models.TextField(blank=True, db_comment='活动备注信息', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='restaurant_id',
            field=models.ForeignKey(blank=True, db_comment='关联的餐厅ID,外键关联restaurants表', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.restaurant', verbose_name='关联餐厅ID'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='schedule_date',
            field=models.DateField(db_comment='活动发生的具体日期', verbose_name='活动日期'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='schedule_id',
            field=models.UUIDField(db_comment='活动唯一标识符,使用UUID格式', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='活动ID'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='start_time',
            field=models.TimeField(db_comment='活动开始时间', verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='记录最后更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='arrival_date',
            field=models.DateField(db_comment='抵达该目的地的日期', verbose_name='抵达日期'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city_name',
            field=models.CharField(db_comment='目的地城市名称', max_length=100, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country_code',
            field=models.CharField(db_comment='所在国家的ISO 3166-1 alpha-2代码,如CN、US等', max_length=2, verbose_name='国家代码'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='departure_date',
            field=models.DateField(db_comment='离开该目的地的日期', verbose_name='离开日期'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_id',
            field=models.UUIDField(db_comment='目的地唯一标识符,使用UUID格式', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='目的地ID'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_order',
            field=models.IntegerField(db_comment='目的地在行程中的访问顺序', validators=[django.core.validators.MinValueValidator(1)], verbose_name='目的地顺序'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='itinerary',
            field=models.ForeignKey(db_comment='关联的行程,外键关联itinerary表', on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='apps.itinerary', verbose_name='行程'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, db_comment='地理纬度坐标,范围-90到90', decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, db_comment='地理经度坐标,范围-180到180', decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nights',
            field=models.IntegerField(db_comment='在该目的地住宿的晚数,自动计算', validators=[django.core.validators.MinValueValidator(1)], verbose_name='住宿晚数'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.CharField(blank=True, db_comment='所在地区或省份', max_length=100, null=True, verbose_name='地区（如省、州）'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(db_comment='酒店详细地址', verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=apps.models.base.JSONField(db_comment='酒店设施字典,如WiFi、停车场、健身房等', default=dict, verbose_name='设施'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='brand_name',
            field=models.CharField(blank=True, db_comment='酒店所属品牌名称', max_length=100, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='business_facilities',
            field=apps.models.base.JSONField(db_comment='商务设施字典,如会议室、商务中心等', default=dict, verbose_name='商务设施'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(db_comment='标准入住时间', default='14:00', verbose_name='入住时间'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(db_comment='标准退房时间', default='12:00', verbose_name='退房时间'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city_name',
            field=models.CharField(db_comment='酒店所在城市名称', max_length=100, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='contact_email',
            field=models.CharField(blank=True, db_comment='酒店联系邮箱', max_length=255, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='contact_phone',
            field=models.CharField(blank=True, db_comment='酒店联系电话', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country_code',
            field=models.CharField(db_comment='所在国家的ISO 3166-1 alpha-2代码,如CN、US等', max_length=2, verbose_name='国家代码'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_by',
            field=models.CharField(blank=True, db_comment='记录创建人用户名', max_length=50, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='currency',
            field=models.CharField(db_comment='价格货币代码,如CNY、USD等', default='CNY', max_length=3, verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, db_comment='酒店详细描述介绍', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='district',
            field=models.CharField(blank=True, db_comment='酒店所在区域或商圈', max_length=100, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='guest_rating',
            field=models.DecimalField(blank=True, db_comment='客人综合评分,范围0-5', decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='客人评分'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_code',
            field=models.CharField(db_comment='酒店唯一编码,用于系统内部标识和检索', max_length=50, unique=True, verbose_name='酒店代码'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.UUIDField(db_comment='酒店唯一标识符,使用UUID格式', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='酒店ID'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(db_comment='酒店中文名称', max_length=200, verbose_name='酒店名称'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_star',
            field=models.IntegerField(blank=True, db_comment='酒店星级,范围1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='星级'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(blank=True, choices=[('LUXURY', '奢华酒店'), ('BUSINESS', '商务酒店'), ('RESORT', '度假酒店'), ('BOUTIQUE', '精品酒店'), ('HOSTEL', '青年旅舍'), ('APARTMENT', '公寓酒店'), ('HOMESTAY', '民宿'), ('MOTEL', '汽车旅馆'), ('OTHER', '其他')], db_comment='酒店类型,如奢华酒店、商务酒店、度假酒店等', max_length=50, verbose_name='酒店类型'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_gallery',
            field=apps.models.base.JSONField(db_comment='酒店图片库URL数组', default=list, verbose_name='图片库'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, db_comment='地理纬度坐标,范围-90到90', decimal_places=6, max_digits=9, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, db_comment='地理经度坐标,范围-180到180', decimal_places=6, max_digits=9, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='main_image_url',
            field=models.CharField(blank=True, db_comment='酒店主图片URL', max_length=500, verbose_name='主图URL'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='max_price',
            field=models.DecimalField(blank=True, db_comment='最高房价', decimal_places=2, max_digits=10, null=True, verbose_name='最高价格'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='min_price',
            field=models.DecimalField(blank=True, db_comment='最低房价', decimal_places=2, max_digits=10, null=True, verbose_name='最低价格'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='popularity_score',
            field=models.DecimalField(blank=True, db_comment='酒店受欢迎度评分,范围0-5', decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='受欢迎度评分'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_range',
            field=models.CharField(blank=True, db_comment='价格范围描述,如经济型、中档、高档等', max_length=50, verbose_name='价格范围'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='review_count',
            field=models.IntegerField(db_comment='累计评论数量', default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_facilities',
            field=apps.models.base.JSONField(db_comment='房间内设施字典,如空调、电视、保险箱等', default=dict, verbose_name='房间设施'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_types',
            field=apps.models.base.JSONField(db_comment='房型信息字典,包含各种房型及其描述', default=dict, verbose_name='房型信息'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '营业中'), ('INACTIVE', '未营业'), ('RENOVATING', '装修中'), ('CLOSED', '已关闭')], db_comment='酒店当前状态,如营业中、未营业、装修中、已关闭', default='ACTIVE', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='tags',
            field=apps.models.base.JSONField(db_comment='酒店标签字典,存储关键词如商务、亲子、度假等', default=dict, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='updated_by',
            field=models.CharField(blank=True, db_comment='记录更新人用户名', max_length=50, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='version',
            field=models.IntegerField(db_comment='数据版本号,用于版本控制', default=1, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='website',
            field=models.CharField(blank=True, db_comment='酒店官方网站URL', max_length=500, verbose_name='网站'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='budget_flexibility',
            field=models.CharField(blank=True, choices=[('STRICT', '严格'), ('MODERATE', '适中'), ('FLEXIBLE', '灵活')], db_comment='预算灵活性,如严格、适中、灵活', max_length=10, null=True, verbose_name='预算灵活性'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_comment='行程确认时间', null=True, verbose_name='确认时间'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='confirmed_by',
            field=models.CharField(blank=True, db_comment='确认行程的运营人员', max_length=50, null=True, verbose_name='确认人（运营人员）'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='contact_company',
            field=models.CharField(blank=True, db_comment='联系人所在单位或公司', max_length=100, null=True, verbose_name='联系人单位'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='contact_person',
            field=models.CharField(db_comment='联系人姓名', max_length=100, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='contact_phone',
            field=models.CharField(db_comment='联系人电话', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='created_by',
            field=models.CharField(db_comment='行程创建人用户名', max_length=50, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='current_status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('CONFIRMED', '已确认'), ('EXPIRED', '已过期'), ('CANCELLED', '已取消'), ('COMPLETED', '已完成')], db_comment='行程当前状态,如草稿、待审核、已确认等', max_length=20, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='删除时间', null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='departure_city',
            field=models.CharField(db_comment='出发城市名称', max_length=100, verbose_name='出发城市'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True, db_comment='行程详细描述', null=True, verbose_name='行程描述'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(db_comment='行程结束日期', verbose_name='行程结束日期'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='expiration_date',
            field=models.DateField(blank=True, db_comment='行程有效期截止日期', null=True, verbose_name='行程有效期截止日期'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='is_deleted',
            field=models.BooleanField(db_comment='标识是否已删除', default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='is_template',
            field=models.BooleanField(db_comment='标识是否为行程模板', default=False, verbose_name='是否为模板'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='itinerary_id',
            field=models.CharField(db_comment='行程唯一标识符,格式为ITI_YYYYMMDD_XXX', editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='行程唯一标识'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='itinerary_json_data',
            field=models.JSONField(blank=True, db_comment='行程完整结构化JSON数据,包含所有关联数据', null=True, verbose_name='行程结构化JSON数据'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='itinerary_name',
            field=models.CharField(db_comment='行程名称', max_length=100, verbose_name='行程名称'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='last_used',
            field=models.DateTimeField(blank=True, db_comment='模板最后使用时间', null=True, verbose_name='模板最后使用时间'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='return_city',
            field=models.CharField(db_comment='返回城市名称', max_length=100, verbose_name='返回城市'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='review_deadline',
            field=models.DateTimeField(blank=True, db_comment='审核截止时间', null=True, verbose_name='审核截止时间'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(db_comment='行程开始日期', verbose_name='行程开始日期'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='template_category',
            field=models.CharField(blank=True, choices=[('HONEYMOON', '蜜月'), ('FAMILY', '家庭'), ('ADVENTURE', '冒险'), ('CITY_TOUR', '城市游览'), ('BEACH', '海滩'), ('CULTURAL', '文化'), ('CUSTOM', '自定义')], db_comment='模板分类,如蜜月、家庭、冒险等', max_length=20, null=True, verbose_name='模板分类'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='template_name',
            field=models.CharField(blank=True, db_comment='模板名称', max_length=100, null=True, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='total_budget',
            field=models.DecimalField(blank=True, db_comment='行程总预算金额', decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总预算'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='total_days',
            field=models.IntegerField(db_comment='行程总天数,自动计算', verbose_name='总天数'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='travel_purpose',
            field=models.CharField(choices=[('LEISURE', '休闲'), ('BUSINESS', '商务'), ('HONEYMOON', '蜜月'), ('FAMILY', '家庭'), ('ADVENTURE', '冒险'), ('CULTURAL', '文化'), ('OTHER', '其他')], db_comment='旅行目的,如休闲、商务、蜜月等', max_length=20, verbose_name='旅行目的'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='updated_by',
            field=models.CharField(blank=True, db_comment='行程更新人用户名', max_length=50, null=True, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='usage_count',
            field=models.IntegerField(db_comment='模板被使用的次数', default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='模板使用次数'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='version',
            field=models.IntegerField(db_comment='数据版本号,用于版本控制', default=1, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='assumptions',
            field=apps.models.base.JSONField(db_comment='系统推断说明列表', default=list, verbose_name='系统推断说明'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='avoid_activities',
            field=apps.models.base.JSONField(blank=True, db_comment='避免的活动列表', default=list, verbose_name='避免活动'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='budget_currency',
            field=models.CharField(db_comment='预算货币代码,如CNY、USD等', default='CNY', max_length=10, verbose_name='预算货币'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='budget_level',
            field=models.CharField(blank=True, choices=[('Economy', '经济'), ('Comfort', '舒适'), ('HighEnd', '高端'), ('Luxury', '奢华')], db_comment='预算等级,如经济、舒适、高端、奢华', max_length=20, verbose_name='预算等级'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='budget_max',
            field=models.DecimalField(blank=True, db_comment='最高预算金额', decimal_places=2, max_digits=10, null=True, verbose_name='最高预算'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='budget_min',
            field=models.DecimalField(blank=True, db_comment='最低预算金额', decimal_places=2, max_digits=10, null=True, verbose_name='最低预算'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='budget_notes',
            field=models.TextField(blank=True, db_comment='预算说明', verbose_name='预算说明'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_by',
            field=models.CharField(blank=True, db_comment='需求创建人用户名', max_length=100, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='destination_cities',
            field=apps.models.base.JSONField(db_comment='目的地城市列表', default=list, verbose_name='目的地城市列表'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_comment='需求过期时间', null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='extension',
            field=apps.models.base.JSONField(blank=True, db_comment='扩展字段字典', default=dict, verbose_name='扩展字段'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='group_adults',
            field=models.IntegerField(db_comment='成人数量', default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成人数量'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='group_children',
            field=models.IntegerField(db_comment='儿童数量', default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='儿童数量'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='group_seniors',
            field=models.IntegerField(db_comment='老人数量', default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='老人数量'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='group_total',
            field=models.IntegerField(db_comment='出行总人数', validators=[django.core.validators.MinValueValidator(1)], verbose_name='总人数'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='hotel_level',
            field=models.CharField(blank=True, choices=[('Economy', '经济型'), ('Comfort', '舒适型'), ('Premium', '高档型'), ('Luxury', '豪华型')], db_comment='酒店等级,如经济型、舒适型、高档型、豪华型', max_length=20, verbose_name='酒店等级'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='hotel_requirements',
            field=models.TextField(blank=True, db_comment='住宿特殊要求', verbose_name='住宿特殊要求'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_template',
            field=models.BooleanField(db_comment='标识是否为需求模板', default=False, verbose_name='是否模板'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='must_visit_spots',
            field=apps.models.base.JSONField(blank=True, db_comment='必游景点列表', default=list, verbose_name='必游景点'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='origin_code',
            field=models.CharField(blank=True, db_comment='出发地城市代码', max_length=10, verbose_name='出发地代码'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='origin_input',
            field=models.TextField(blank=True, db_comment='客户原始的自然语言输入', verbose_name='客户原始输入'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='origin_name',
            field=models.CharField(db_comment='出发地城市名称', max_length=100, verbose_name='出发地名称'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='origin_type',
            field=models.CharField(blank=True, db_comment='出发地类型', max_length=20, verbose_name='出发地类型'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='preference_tags',
            field=apps.models.base.JSONField(blank=True, db_comment='偏好标签列表', default=list, verbose_name='偏好标签'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_id',
            field=models.CharField(db_comment='需求唯一标识符,格式为REQ_YYYYMMDD_XXX', editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='需求ID'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_json_data',
            field=apps.models.base.JSONField(db_comment='需求结构化JSON数据', default=dict, verbose_name='JSON结构数据'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='reviewed_by',
            field=models.CharField(blank=True, db_comment='需求审核人用户名', max_length=100, null=True, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='source_type',
            field=models.CharField(choices=[('NaturalLanguage', '自然语言输入'), ('FormInput', '表单输入')], db_comment='需求来源,如自然语言输入、表单输入', default='NaturalLanguage', max_length=20, verbose_name='需求来源'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('PendingReview', '待审核'), ('Confirmed', '已确认'), ('Expired', '已过期')], db_comment='需求状态,如待审核、已确认、已过期', default='PendingReview', max_length=20, verbose_name='需求状态'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='template_category',
            field=models.CharField(blank=True, db_comment='模板分类', max_length=100, verbose_name='模板分类'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='template_name',
            field=models.CharField(blank=True, db_comment='模板名称', max_length=200, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='transportation_notes',
            field=models.TextField(blank=True, db_comment='交通偏好说明', verbose_name='交通偏好说明'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='transportation_type',
            field=models.CharField(blank=True, choices=[('RoundTripFlight', '双飞'), ('OneWayFlight', '单飞'), ('HighSpeedTrain', '高铁'), ('Train', '火车'), ('SelfDriving', '自驾'), ('Other', '其他')], db_comment='大交通方式,如双飞、高铁、自驾等', max_length=20, verbose_name='大交通方式'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='travel_date_flexible',
            field=models.BooleanField(db_comment='标识出行日期是否灵活可调', default=False, verbose_name='日期是否灵活'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='travel_end_date',
            field=models.DateField(blank=True, db_comment='出行结束日期', null=True, verbose_name='出行结束日期'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='travel_start_date',
            field=models.DateField(blank=True, db_comment='出行开始日期', null=True, verbose_name='出行开始日期'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='trip_days',
            field=models.IntegerField(db_comment='出行天数,范围1-365', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='出行天数'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='trip_rhythm',
            field=models.CharField(blank=True, choices=[('Relaxed', '悠闲'), ('Moderate', '适中'), ('Intense', '紧凑')], db_comment='行程节奏,如悠闲、适中、紧凑', max_length=20, verbose_name='行程节奏'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(db_comment='餐厅详细地址', verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='alcohol_served',
            field=models.BooleanField(blank=True, db_comment='标识是否提供酒精饮料', null=True, verbose_name='是否提供酒精饮料'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='amenities',
            field=apps.models.base.JSONField(db_comment='餐厅设施字典,如WiFi、停车场、包间等', default=dict, verbose_name='设施'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='avg_price_per_person',
            field=models.DecimalField(blank=True, db_comment='人均消费价格', decimal_places=2, max_digits=10, null=True, verbose_name='人均价格'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='chef_name',
            field=models.CharField(blank=True, db_comment='主厨姓名', max_length=100, verbose_name='主厨名字'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city_name',
            field=models.CharField(db_comment='餐厅所在城市名称', max_length=100, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_email',
            field=models.CharField(blank=True, db_comment='餐厅联系邮箱', max_length=255, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_phone',
            field=models.CharField(blank=True, db_comment='餐厅联系电话', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country_code',
            field=models.CharField(db_comment='所在国家的ISO 3166-1 alpha-2代码,如CN、US等', max_length=2, verbose_name='国家代码'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_by',
            field=models.CharField(blank=True, db_comment='记录创建人用户名', max_length=50, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(db_comment='餐厅主菜系,如中餐、西餐、日料等', max_length=100, verbose_name='菜系'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, db_comment='餐厅详细描述介绍', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dietary_options',
            field=apps.models.base.JSONField(db_comment='饮食选项字典,如素食、无麸质等', default=dict, verbose_name='饮食选项'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.CharField(blank=True, db_comment='餐厅所在区域或商圈', max_length=100, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='food_rating',
            field=models.DecimalField(blank=True, db_comment='食物评分,范围0-5', decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='食物评分'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_24_hours',
            field=models.BooleanField(db_comment='标识餐厅是否24小时营业', default=False, verbose_name='是否24小时营业'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='main_image_url',
            field=models.CharField(blank=True, db_comment='餐厅主图片URL', max_length=500, verbose_name='主图URL'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours',
            field=apps.models.base.JSONField(db_comment='营业时间字典,包含每日营业时段', default=dict, verbose_name='营业时间'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='popularity_score',
            field=models.DecimalField(blank=True, db_comment='餐厅受欢迎度评分,范围0-5', decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='受欢迎度评分'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(choices=[('$', '经济型'), ('$$', '中档'), ('$$$', '高档'), ('$$$$', '奢华')], db_comment='价格范围,如经济型、中档、高档、奢华', max_length=50, verbose_name='价格范围'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='private_rooms_available',
            field=models.BooleanField(db_comment='标识是否有包间', default=False, verbose_name='是否有包间'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='reservation_required',
            field=models.BooleanField(db_comment='标识是否需要提前预订', default=False, verbose_name='是否需要预订'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='reservation_website',
            field=models.CharField(blank=True, db_comment='预订网站URL', max_length=500, verbose_name='预订网站'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_code',
            field=models.CharField(db_comment='餐厅唯一编码,用于系统内部标识和检索', max_length=50, unique=True, verbose_name='餐厅代码'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_id',
            field=models.UUIDField(db_comment='餐厅唯一标识符,使用UUID格式', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='餐厅ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(db_comment='餐厅中文名称', max_length=200, verbose_name='餐厅名称'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(blank=True, choices=[('FINE_DINING', '精致餐饮'), ('CASUAL', '休闲餐饮'), ('FAST_FOOD', '快餐'), ('CAFE', '咖啡馆'), ('BAR', '酒吧'), ('STREET_FOOD', '街头美食'), ('BUFFET', '自助餐'), ('OTHER', '其他')], db_comment='餐厅类型,如精致餐饮、休闲餐饮、快餐等', max_length=50, verbose_name='餐厅类型'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(db_comment='累计评论数量', default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='seating_capacity',
            field=models.IntegerField(blank=True, db_comment='餐厅总座位数', null=True, verbose_name='座位数'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='service_rating',
            field=models.DecimalField(blank=True, db_comment='服务评分,范围0-5', decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='服务评分'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='signature_dishes',
            field=apps.models.base.JSONField(db_comment='招牌菜字典', default=dict, verbose_name='招牌菜'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '营业中'), ('INACTIVE', '未营业'), ('TEMPORARILY_CLOSED', '临时关闭'), ('PERMANENTLY_CLOSED', '永久关闭')], db_comment='餐厅当前状态,如营业中、未营业、临时关闭、永久关闭', default='ACTIVE', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sub_cuisine_types',
            field=apps.models.base.JSONField(db_comment='子菜系列表,如川菜、粤菜等', default=list, verbose_name='子菜系数组'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=apps.models.base.JSONField(db_comment='餐厅标签字典,存储关键词如商务、约会、家庭等', default=dict, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='updated_by',
            field=models.CharField(blank=True, db_comment='记录更新人用户名', max_length=50, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='version',
            field=models.IntegerField(db_comment='数据版本号,用于版本控制', default=1, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.CharField(blank=True, db_comment='餐厅官方网站URL', max_length=500, verbose_name='网站'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='year_established',
            field=models.IntegerField(blank=True, db_comment='餐厅建立年份', null=True, verbose_name='建立年份'),
        ),
        migrations.AlterField(
            model_name='travelerstats',
            name='adult_count',
            field=models.IntegerField(db_comment='成人数量,一般指18-60岁', default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成人数'),
        ),
        migrations.AlterField(
            model_name='travelerstats',
            name='child_count',
            field=models.IntegerField(db_comment='儿童数量,一般指3-12岁', default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='儿童数'),
        ),
        migrations.AlterField(
            model_name='travelerstats',
            name='infant_count',
            field=models.IntegerField(db_comment='婴儿数量,一般指0-2岁', default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='婴儿数'),
        ),
        migrations.AlterField(
            model_name='travelerstats',
            name='itinerary',
            field=models.ForeignKey(db_comment='关联的行程,外键关联itinerary表', on_delete=django.db.models.deletion.CASCADE, related_name='traveler_stats', to='apps.itinerary', verbose_name='行程'),
        ),
        migrations.AlterField(
            model_name='travelerstats',
            name='notes',
            field=models.TextField(blank=True, db_comment='备注信息', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='travelerstats',
            name='senior_count',
            field=models.IntegerField(db_comment='老人数量,一般指60岁以上', default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='老人数'),
        ),
        migrations.AlterField(
            model_name='travelerstats',
            name='stat_id',
            field=models.UUIDField(db_comment='统计记录唯一标识符,使用UUID格式', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='统计ID'),
        ),
    ]
