# Generated by Django 5.2.10 on 2026-02-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_attraction_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='category',
            field=models.CharField(blank=True, choices=[('NATURAL', '自然景观'), ('HISTORICAL', '历史古迹'), ('CULTURAL', '文化景点'), ('RELIGIOUS', '宗教场所'), ('MODERN', '现代景点'), ('ENTERTAINMENT', '娱乐场所'), ('SHOPPING', '购物场所'), ('OUTDOOR', '户外景点'), ('INDOOR', '室内景点'), ('OTHER', '其他')], db_comment='景点主分类,如自然景观，历史古迹，文化景点，宗教场所，现代景点，娱乐场所，购物场所，户外景点，室内景点，其他', max_length=50, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '营业中'), ('INACTIVE', '非营业中'), ('UNDER_CONSTRUCTION', '建设中'), ('CLOSED', '已关闭')], db_comment='景点当前状态,如营业中、关闭、维修中等', max_length=20, verbose_name='状态'),
        ),
    ]
