# Generated by Django 5.2.11 on 2026-03-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_attraction_category_alter_attraction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='contact_company',
            field=models.CharField(blank=True, db_comment='联系人所在单位或公司', max_length=100, null=True, verbose_name='联系人单位'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='contact_person',
            field=models.CharField(blank=True, db_comment='联系人姓名', default='', max_length=100, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='contact_phone',
            field=models.CharField(blank=True, db_comment='联系人电话', default='', max_length=20, verbose_name='联系电话'),
        ),
    ]
