# Generated by Django 5.2.8 on 2026-03-05 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_requirement_contact_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='origin_type',
            field=models.CharField(blank=True, choices=[('Domestic', '国内'), ('International', '国际')], db_comment='出发地类型', max_length=20, verbose_name='出发地类型'),
        ),
        migrations.CreateModel(
            name='RequirementItinerary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(db_comment='自增主键ID', primary_key=True, serialize=False, verbose_name='自增主键')),
                ('itinerary', models.ForeignKey(db_comment='关联至itineraries表的主键', on_delete=django.db.models.deletion.CASCADE, to='apps.itinerary', verbose_name='行程')),
                ('requirement', models.ForeignKey(db_comment='关联至requirements表的主键', on_delete=django.db.models.deletion.CASCADE, to='apps.requirement', verbose_name='需求')),
            ],
            options={
                'verbose_name': '需求与行程关联关系',
                'verbose_name_plural': '需求与行程关联关系',
                'db_table': 'requirement_itinerary',
                'db_table_comment': '存储requirement与itinerary之间的一对多关联关系',
                'unique_together': {('requirement', 'itinerary')},
            },
        ),
    ]
