# Generated by Django 5.2.11 on 2026-03-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_alter_requirement_origin_type_requirementitinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='district',
            field=models.CharField(blank=True, db_comment='景点所属的行政区域和商业圈信息，如"朝阳区-三里屯商圈"或"浦东新区-陆家嘴商圈"', max_length=200, null=True, verbose_name='区域和商圈'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attraction_code',
            field=models.CharField(blank=True, db_comment='景点唯一编码,用于系统内部标识和检索', max_length=50, null=True, unique=True, verbose_name='景点代码'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='country_code',
            field=models.CharField(blank=True, db_comment='所在国家的ISO 3166-1 alpha-2代码,如CN、US等', max_length=2, null=True, verbose_name='国家代码'),
        ),
        migrations.AlterField(
            model_name='requirementitinerary',
            name='itinerary',
            field=models.ForeignKey(db_comment='关联至itineraries表的主键', on_delete=django.db.models.deletion.CASCADE, related_name='requirement_itineraries', to='apps.itinerary', verbose_name='行程'),
        ),
    ]
