# Generated by Django 5.2.11 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_attraction_district_alter_attraction_attraction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='pricing_strategy',
            field=models.TextField(blank=True, db_comment='景点详细定价策略说明,包括不同票种、优惠政策、套票组合等定价规则', null=True, verbose_name='定价策略'),
        ),
    ]
