# Generated by Django on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_attraction_pricing_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='itinerary_quote',
            field=models.TextField(blank=True, null=True, verbose_name='行程报价', db_comment='行程报价详情'),
        ),
    ]
