# Generated by Django 5.2.12 on 2026-03-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_itinerary_trip_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='itinerary_quote_json_data',
            field=models.TextField(blank=True, db_comment='行程报价的JSON结构化数据', null=True, verbose_name='行程报价JSON数据'),
        ),
    ]
