# Generated by Django 5.2.12 on 2026-03-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_itinerary_itinerary_quote_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='pricing_strategy',
            field=models.TextField(blank=True, db_comment='酒店的定价策略信息', null=True, verbose_name='定价策略'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pricing_strategy',
            field=models.TextField(blank=True, db_comment='餐厅的定价策略信息', null=True, verbose_name='定价策略'),
        ),
    ]
