# Generated by Django 5.2.12 on 2026-03-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_hotel_pricing_strategy_restaurant_pricing_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_code',
            field=models.CharField(blank=True, db_comment='酒店唯一编码,用于系统内部标识和检索', default='', max_length=50, verbose_name='酒店代码'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='current_status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('CONFIRMED', '已确认'), ('EXPIRED', '已作废'), ('CANCELLED', '已取消'), ('COMPLETED', '已完成')], db_comment='行程当前状态,如草稿、待审核、已确认等', max_length=20, verbose_name='当前状态'),
        ),
    ]
