# Generated by Django 5.2.12 on 2026-03-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_alter_hotel_hotel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_code',
            field=models.CharField(blank=True, db_comment='餐厅唯一编码,用于系统内部标识和检索', default='', max_length=50, verbose_name='餐厅代码'),
        ),
    ]
