# Generated by Django 5.2.12 on 2026-03-22 09:08

import apps.models.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_alter_restaurant_restaurant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='district',
            field=apps.models.base.JSONField(blank=True, db_comment='目的地区域和商圈列表，如["朝阳区", "国贸"]', default=list, verbose_name='区域和商圈'),
        ),
    ]
