# Generated by Django 5.2.12 on 2026-03-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_requirement_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='destination_cities',
            field=models.CharField(db_comment='目的地城市列表', default='', max_length=500, verbose_name='目的地城市(逗号分隔)'),
        ),
    ]
