# Generated by Django 5.2.12 on 2026-03-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_alter_requirement_destination_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='contact_email',
            field=models.CharField(blank=True, db_comment='联系人电子邮件', default='', max_length=255, verbose_name='联系人电子邮件'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='contact_email',
            field=models.CharField(blank=True, db_comment='联系人电子邮件', default='', max_length=255, verbose_name='联系人电子邮件'),
        ),
    ]
